node(){
    echo "===================================Environment variables starts==================================="
		sh "env"
	echo "===================================Environment variables ends==================================="
    switch(env.gitlabActionType) {
		case 'PUSH':
                 echo "===================================PUSH event starts==================================="
                 switch(env.gitlabTargetBranch){
                     case 'Master':
                        echo "Master Branch"
                        checkoutGitlab('TSAR')
						executeBuildCommands()
                 }
	}
}

def checkoutGitlab(branch){
    stage('checkout'){
        checkout(
				[
					$class: 'GitSCM',
					branches: [[name: "*/${branch}"]],
					doGenerateSubmoduleConfigurations: false,
					extensions: [],
					submoduleCfg: [],
					userRemoteConfigs: [[
						credentialsId: 'suresh_chouksey',
						url: 'https://git.fulcrumww.com/BAXA_Grp/BAXA_PoSServices'
					]]
				]
			)

    }
}

def executeBuildCommands(){
	stage("Buid process"){
		sh "sudo chmod -R 777 /opt/jenkins/workspace"
		//for (int i = 0; i < projects.size(); i++) {
			sh "( cd ${workspace}/testPipeline ; mvn clean install -U )"
		//}
	}
}
