node(){
    echo "===================================Environment variables starts==================================="
		sh "env"
	echo "===================================Environment variables ends==================================="
    switch(env.gitlabActionType) {
		case 'PUSH':
                 echo "===================================PUSH event starts==================================="
                 switch(env.gitlabTargetBranch){
                     case 'Master':
                        echo "Master Branch"
                        checkoutGitlab('TSAR')

                 }
	}
}

def checkoutGitlab(branch){
    stage('checkout'){
        checkout(
				[
					$class: 'GitSCM',
					branches: [[name: "*/${branch}"]],
					doGenerateSubmoduleConfigurations: false,
					extensions: [],
					submoduleCfg: [],
					userRemoteConfigs: [[
						credentialsId: 'suresh_chouksey',
						url: 'https://git.fulcrumww.com/BAXA_Grp/BAXA_PoSServices'
					]]
				]
			)

    }
}